[package]
name = "keystroks_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.libc]
version = "0.2.144"
[dependencies.libloading]
version = "0.8"